# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version=1.0.0-beta.5
maven_group=me.flashyreese.mods
archives_name=nuit
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.11

# Dependencies
architectury_api_version=17.0.8
fabric_loader_version=0.18.4
fabric_api_version=0.141.3+1.21.11
neoforge_version=21.11.40-beta
